# .golangci.toml
version = "2"

[linters]
  default = "all"
  disable = [
    "lll",
    "dupl",
    "funlen",
    "nestif",
    "wsl",
    "gochecknoinits",
    "exhaustruct",
  ]

  [linters.settings]
    [linters.settings.gocritic]
      enabled-tags = ["performance", "style", "experimental"]
      disabled-checks = ["hugeParam"]

    [linters.settings.gocyclo]
      min-complexity = 15  # Default is 30 (we are more strict)

    [linters.settings.gocognit]
      min-complexity = 15  # Default is 30 (we are more strict)

    [linters.settings.prealloc]
      simple = true
      range-loops = true

    [linters.settings.errcheck]
      check-type-assertions = true
      check-blank = true

    [linters.settings.depguard.rules.main]
      list-mode = "lax"
      allow = [
        "botex/pkg/logger",
        "botex/pkg/message",
        "go.mau.fi/whatsmeow/types"
      ]

    [linters.settings.revive]
      rules = [
        { name = "exported", disabled = true }
      ]

[formatters]
  enable = ["gofumpt", "goimports", "gci"]
  [formatters.settings.gci]
    sections = ["standard", "default", "prefix(github.com/totallynotdavid/BoTeX)"]

[run]
  timeout = "5m"
  concurrency = 4
  tests = true
  modules-download-mode = "readonly"
  allow-parallel-runners = true

[issues]
  max-issues-per-linter = 0
  max-same-issues = 0
  fix = true

[severity]
  default = "error"
